### SIGN UP USER
POST http://localhost:3000/api/auth/sign-up/email
Accept: application/json
Content-Type: application/json

{
  "name": "testuser3",
  "email": "testuser3@example.com",
  "password": "testuser3password12345"
}

### SIGN IN USER

POST http://localhost:3000/api/auth/sign-in/email
Accept: application/json
Content-Type: application/json
Origin: http://localhost:3000

{
  "email": "testuser2@example.com",
  "password": "1234567890"
}

### UPDATE USER
PATCH http://localhost:3000/api/users/me
Accept: application/json
Content-Type: application/json
Authorization: Bearer OGhXfSMoEMvnzShxptJEfbnJqXjIVLBF

{
  "name": "updatedtestuser1"
}

### GET USER
GET http://localhost:3000/api/users/me
Accept: application/json
Authorization: Bearer OGhXfSMoEMvnzShxptJEfbnJqXjIVLBF

### LOGOUT USER
POST http://localhost:3000/api/auth/sign-out
Accept: application/json
Content-Type: application/json
Authorization: Bearer OGhXfSMoEMvnzShxptJEfbnJqXjIVLBF
Origin: http://localhost:3000

{}